name: Scrape VVZ and copy to nethz

on: [workflow_dispatch]

jobs:
    scrape_vvz:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Prepare output directory
              run: mkdir -p dist
              
            - name: Scrape VVZ
              run: node scraper.js -l en -d "Computer Science Bachelor" -s 2023W -o dist/HS23.json

            - name: Ensure sshpass is installed
              run: sudo apt install sshpass

            - name: Deploy to nethz
              run: sshpass -p '${{secrets.NETHZ_PASSWORD}}' rsync -e "ssh -o StrictHostKeyChecking=no" -avz dist/ ${{secrets.NETHZ_USERNAME}}@slab1.ethz.ch:~/homepage/eth-sem-planner
